name: Fetch Stock Data

on:
  schedule:
    # Runs every day at 11:00 UTC = 18:00 WIB (Jakarta)
    - cron: "0 11 * * *"
  workflow_dispatch: # Allow manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run stock fetch script
        run: |
          python scraper.py $(date -d '+7 hours' +'%Y-%m-%d')

      - name: Commit and push CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add data/*.csv
          
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add stock data for $(date -u +"%Y-%m-%d")"
            git push origin HEAD
          fi
